import type { OversightRecord } from "../types/index.js"

export function generateOversightMd(decisions: OversightRecord[]): string {
  const active = decisions.filter((d) => d.status === "active")
  const now = new Date().toISOString()

  const lines: string[] = [
    "# OVERSIGHT.md",
    "",
    "> Auto-generated architectural constraints for AI agents.",
    "> Read this at the start of every session. Do not delete.",
    `> Last updated: ${now}`,
    "",
    "---",
    "",
  ]

  const mustConstraints = active.flatMap((d) =>
    d.constraints
      .filter((c) => c.severity === "must")
      .map((c) => ({ constraint: c, decision: d }))
  )

  const doNotChangeAll = active.flatMap((d) => d.doNotChange.map((p) => ({ pattern: p, decision: d })))

  if (mustConstraints.length > 0) {
    lines.push("## Hard Constraints (must)")
    lines.push("")
    lines.push("These are non-negotiable. Violating them will be blocked in enforcement mode.")
    lines.push("")
    for (const { constraint, decision } of mustConstraints) {
      lines.push(`- **${constraint.description}**`)
      if (constraint.rationale) lines.push(`  - Rationale: ${constraint.rationale}`)
      lines.push(`  - Source: [${decision.title}]`)
    }
    lines.push("")
  }

  const shouldConstraints = active.flatMap((d) =>
    d.constraints
      .filter((c) => c.severity === "should")
      .map((c) => ({ constraint: c, decision: d }))
  )

  if (shouldConstraints.length > 0) {
    lines.push("## Soft Constraints (should)")
    lines.push("")
    for (const { constraint, decision } of shouldConstraints) {
      lines.push(`- ${constraint.description}`)
      lines.push(`  - Source: [${decision.title}]`)
    }
    lines.push("")
  }

  if (doNotChangeAll.length > 0) {
    lines.push("## Do-Not-Change Patterns")
    lines.push("")
    lines.push("Do not modify these files, functions, or patterns without first reviewing the associated decision:")
    lines.push("")
    for (const { pattern, decision } of doNotChangeAll) {
      lines.push(`- \`${pattern}\` — [${decision.title}]`)
    }
    lines.push("")
  }

  if (active.length > 0) {
    lines.push("## Decision Summaries")
    lines.push("")
    for (const d of active) {
      lines.push(`### ${d.title}`)
      if (d.summary) lines.push(`> ${d.summary}`)
      lines.push("")
      if (d.decision) lines.push(`**Decision:** ${d.decision}`)
      if (d.rationale) lines.push(`**Rationale:** ${d.rationale}`)
      if (d.anchors.length > 0) {
        lines.push(`**Anchors:** ${d.anchors.map((a) => `\`${a.path}\``).join(", ")}`)
      }
      if (d.agentHints.length > 0) {
        lines.push(`**Agent hints:**`)
        for (const hint of d.agentHints) {
          lines.push(`  - ${hint.instruction}`)
        }
      }
      lines.push("")
    }
  }

  lines.push("---")
  lines.push("*Generated by [Oversight](https://github.com/rudraptpsingh/oversight)*")
  lines.push("")

  return lines.join("\n")
}
